name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Identify LaTeX docuemnts
        run: echo "TEX_FILES=$(find . -name '*.tex' | tr '\n' ' ')" >> $GITHUB_ENV
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.TEX_FILES }}
      - name: Purge non-essential files
        run: |
          find . -type f ! \( -iname "*.pdf" -o -iname "*.html" \) -delete
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
